### PR TITLE
having custom health amount on a spaz

### LINKED ISSUE #688: Alterable Health amount
I think we should let hitpoints (hitpoints_max) be changeable by default, ik someone else had done it before in their modpacks, but I want it to be changeable by anyone (who open internal code like me) easily, so they might add bots with extra health (what I did), special powerup (that could interfere with hitpoints) , or you name it.
`#code from spaz.py
    class Spaz(bs.Actor):
    """
    Base class for various Spazzes.

    Category: **Gameplay Classes**

    A Spaz is the standard little humanoid character in the game.
    It can be controlled by a player or by AI, and can have
    various different appearances.  The name 'Spaz' is not to be
    confused with the 'Spaz' character in the game, which is just
    one of the skins available for instances of this class.
    """

    # pylint: disable=too-many-public-methods
    # pylint: disable=too-many-locals

    node: bs.Node
    """The 'spaz' bs.Node."""

    points_mult = 1
    curse_time: float | None = 5.0
    default_bomb_count = 1
    default_bomb_type = 'normal'
    default_boxing_gloves = False
    default_shields = False
    hitpoints = 1000 #put hitpoint value here for it to be alterable on demand.
    hitpoints_max = 1000`

IMG_0329
_This is a bot I've custom made with extra health points._

#689

### PR DESCRIPTION
**Pull request by MW2917**
It's perfect for anyone who wanted an even tougher bot, powerups that can interfere with health (I already thought of steroids (Now to figure out how the hell do I make a powerup))  or any mods on mechanics they can think of without making this change manually everytime.

This closes #688 

## Type of Changes

|     | Type                   |
|-----|------------------------|
| ✓   | :sparkles: New feature |
| ✓   | :hammer: Fix what I think was a bug.   |
| ✓   | :scroll: Great for change modders         |

### CODE REVIEW

**Review by EraOSBeta — CHANGES_REQUESTED** [review]
It's not really useful since you can simply change those values the moment spaz is created; but if this goes through in my opinion it's better to do `default_hitpoints_max = 1000` instead of the 2 lines you added and then do `self.hitpoints = self.default_hitpoints_max` and `self.hitpoints_max = self.default_hitpoints_max` instead of the 2 lines you removed, since having to set hitpoints and hitpoints_max separately before spawning spaz doesn't make a whole lot of sense.

**Comment by MW2917** [comment]
> It's not really useful since you can simply change those values the moment spaz is created; but if this goes through in my opinion it's better to do `default_hitpoints_max = 1000` instead of the 2 lines you added and then do `self.hitpoints = self.default_hitpoints_max` and `self.hitpoints_max = self.default_hitpoints_max` instead of the 2 lines you removed, since having to set hitpoints and hitpoints_max separately before spawning spaz doesn't make a whole lot of sense.

yeah just like the curse time thing. thx

**Review by EraOSBeta — APPROVED** [review]
Seems pretty good. Now we just need eric to approve workflow runs so we can see if all checks pass or not (I'm too lazy to run checks locally right now)

**Comment by efroemling** [comment]
Looks good to me. Thanks for the improvement!

**Pull request merged**
