### PR TITLE
BombSquad Exclusive Emojis

### PR DESCRIPTION
**Pull request by Benefit-Zebra**
## Description
Internal Game Keyboard now has a new Shiny Emoji widget.
Also added Continuous CAPITAL letters feature. 

## Type of Changes
|   | Type |
| ------------- | ------------- |
| ✓  | :sparkles: New feature | |

## Related Issue
#119

### CODE REVIEW

**Comment by PythonCode-blip** [comment]
Thank you

**Comment by efroemling** [comment]
Thanks for putting this together!

I'd like to request one change though:
Could you limit the available emojis to 'standard' ones and not the special built-in ones?

I'd like to reserve the game's built-in icons for special uses such as account/profile icons and things like that. I know people make use of them in a lot of places currently such as public party names but I plan to start clamping down on that sort of usage at some point. I'm hoping to start associating them with more things like ranks or achievements and if they're used everywhere it sort of diminishes their meaning.

**Comment by Benefit-Zebra** [comment]
Ok @efroemling I will today remove the built-in special ones. And this PR will be updated by me tomorrow.

**Comment by efroemling** [comment]
> Ok @efroemling I will today remove the built-in special ones. And this PR will be updated by me tomorrow.

Thanks a ton!

**Comment by Benefit-Zebra** [comment]
Though @efroemling the fact is **your** and **mine** _time zone_ are **_12 hours 30 minutes apart_**.

**Comment by efroemling** [comment]
> Though @efroemling the fact is **your** and **mine** _time zone_ are **_12 hours 30 minutes apart_**.

Haha; well hello from the opposite side of the planet!

**Comment by Benefit-Zebra** [comment]
> Haha; well hello from the opposite side of the planet!
Hello to other side of the world too!!

**Comment by Benefit-Zebra** [comment]
@efroemling Even though we remove the in bulit BombSquad emojis, modders will do try to write mods to get them in the Internal Game Keyboard using the _snowypowerup_ method.

**Comment by PythonCode-blip** [comment]
Hey Mr Froemling, can you please fix the internal keyboard type delay but thing, I don't know if it's a big but it can kinda annoy the user who types and turns out like this "Hl lrd" when it was supposed to be "Hello World", this right here is a problem for fast handiwork. And could you also add a caps lock button because in order for the text to be all capitals, you have to type a word one at a time and then put shift, this could really help for the fast people who have fast handiwork. Thank you for reading this Mr. Froemling.

**Comment by efroemling** [comment]
> @efroemling Even though we remove the built-in special ones, modders will do try to write mods to get them in the Internal Game Keyboard using the _snowypowerup_ method.

That's ok. I know I can't keep modders from doing their thing; I just want to prevent normal people from using them since they might soon no longer appear in cases such as public party names or chat messages and I don't want to confuse people.

**Comment by efroemling** [comment]
> Hey Mr Froemling, can you please fix the internal keyboard type delay but thing, I don't know if it's a big but it can kinda annoy the user who types and turns out like this "Hl lrd" when it was supposed to be "Hello World", this right here is a problem for fast handiwork. And could you also add a caps lock button because in order for the text to be all capitals, you have to type a word one at a time and then put shift, this could really help for the fast people who have fast handiwork. Thank you for reading this Mr. Froemling.

Interesting; I didn't know this was an issue but I just reproduced it on my device. I would like to fix this if possible. Could you create a separate issue for this in the issues section? (or is there one already?)

**Comment by Benefit-Zebra** [comment]
> And could you also add a caps lock button because in order for the text to be all capitals, you have to type a word one at a time and then put shift, this could really help for the fast people who have fast handiwork. Thank you for reading this Mr. Froemling.

I have added the continuos CAPITAL letters feature.

**Comment by PythonCode-blip** [comment]
> Interesting; I didn't know this was an issue but I just reproduced it on my device. I would like to fix this if possible. Could you create a separate issue for this in the issues section? (or is there one already?)

Actually, the issue was here years ago since. Alright, I will. Not yet.

**Comment by Benefit-Zebra** [comment]
@efroemling PR is ready to be merged. I removed the in-built special ones.

**Pull request merged**
