### PR TITLE
changing device name for servers

### PR DESCRIPTION
**Pull request by imayushsaini**
party name as device name for headless 🤔.

### CODE REVIEW

**Comment by fraq-sss** [comment]
I support, good idea!

**Comment by imayushsaini** [comment]
> I support, good idea! But that's not good if server name is long.

This name will appear only on ballistica.net/devices not ServerXXXX of game roster.
So long server name doesn't matter (can set limit on frontend if it breaks UI).

**Comment by efroemling** [comment]
Looks good to me; thanks!

My one thought: would you mind if we went with BA_DEVICE_NAME instead of BA_HOST_NAME? Conceptually they are sort of interchangeable but internally the value is accessed via GetDeviceName() so I think this makes it more consistent.

(I'd be happy to pull this in and make that change on my end if you're ok with it)

**Comment by efroemling** [comment]
Thanks again for doing this and for the quick turnaround on the tweak request!

**Pull request merged**
