### PR TITLE
Small docs addition: "How to play custom music"

### PR DESCRIPTION
**Pull request by Dliwk**
# :scroll: Docs

Just a bit addition to docs about ba module. I figured out how to make custom music for about 15 minutes :sweat_smile:

### CODE REVIEW

**Comment by Dliwk** [comment]
Oops ahah.. It doesn't work :disappointed: But how to play custom music?

**Comment by efroemling** [comment]
Currently that function accepts a [MusicType](https://github.com/efroemling/ballistica/blob/master/docs/ba_module.md#class_ba_MusicType) enum which tells the game which a 'type' of music to play. The game has a default file it plays for each type and also the user can override that by creating their own 'Soundtrack'.

Custom soundtracks are implemented on Mac and Android currently.

Perhaps we should modify that function allow passing a filename in directly for cases where modders want to play a specific thing...

**Comment by Dliwk** [comment]
Thanks; I know that this is an enum, but for some reason I thought that if I pass an argument to the constructor, it will create an "unnamed" type of music and this file will be played.

**Comment by efroemling** [comment]
Sadly no; passing a value to an Enum's constructor will simply give you the Enum corresponding to that value. (so MusicType('menu') will give you MusicType.MENU, etc.)

**Comment by efroemling** [comment]
Ok I just pushed a commit which cleans up ba._music stuff a bit so hopefully its easier to see what is going on.

Basically, to play specific music of your own you just need to not use the soundtrack system. So call ba.setmusic(None) and then create a 'sound' node to play whatever you want. See ba._music.MusicController._play_internal_music() for an example.

**Comment by efroemling** [comment]
I'll go ahead and close this, but please don't hesitate to ask if you have any other questions about music playback or if I can clarify anything in the docs/etc.

**Pull request closed without merging**
