### PR TITLE
Github action for nightly build and to make release

### PR DESCRIPTION
**Pull request by Loup-Garou911XD**
## Steps

- [x] Write a good description of what your PR does (and WHY it does it).
- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Add a CHANGELOG entry if your change is non-trivial.
- [x] Ensure `make preflight` completes successfully.

## Description
- Added github action to build docker image and sphinx docs nightly instead of on every commit to save time on checks
- Added github action to release build files on tag push
- Added some comments to makefile docker targets
## Type of Changes

|     | Type                   |
|-----|------------------------|
| ✓   | :sparkles: New feature |

### CODE REVIEW

**Comment by Loup-Garou911XD** [comment]
should the release be release build or debug build?

**Comment by Loup-Garou911XD** [comment]
@efroemling should the releases be release build or debug build??

**Comment by Loup-Garou911XD** [comment]
[here](https://github.com/Loup-Garou911XD/ballistica/releases) if you want to see how release looks

**Comment by Loup-Garou911XD** [comment]
you can edit the body of release manually to highlight major changes or i can write a script that gets everything from CHANGELOG.md like [here on plugman repo](https://github.com/Loup-Garou911XD/plugin-manager/releases)

**Comment by efroemling** [comment]
Thanks for this!

**Pull request merged**
