### PR TITLE
Weak punch sound to reuse (spaz.py)

### PR DESCRIPTION
**Pull request by Ralfreengz**
needs #483 to work

### CODE REVIEW

**Comment by efroemling** [comment]
Hi; was there a reason you closed this? I was planning on taking a look at it soon.

**Comment by efroemling** [comment]
I'd like to pull these in now. Can you pull the latest master and get these tests fixed? Sorry again for being slow.

**Comment by efroemling** [comment]
(just a gentle reminder that this one is still failing. If you can get it passing I can pull both in)

**Comment by Dliwk** [comment]
Here is mypy error which caused CI to fail:
изображение

**Comment by efroemling** [comment]
Oh I'm guessing this is due to the factory changes being in a different branch.  It's all good; I'll go ahead and pull both PRs in and then it should work (and I can fix it if not).

**Pull request merged**
