### PR TITLE
Changing camera attributes from python layer

### PR DESCRIPTION
**Pull request by IvanPragma**
## Steps

- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Add a CHANGELOG entry describing what your PR does.
- [x] Ensure `make preflight` completes successfully.
- [x] Write a good description on what the PR does.

## Description
Now you can change the camera attributes from the python layer, this will give more opportunities to the creators of plugins. The following methods have been added to the _ba module:
- _ba.get_camera_position() -> tuple[float, float, float]
- _ba.get_camera_target() -> tuple[float, float, float]
- _ba.set_camera_position(x: float, y: float, z: float) -> None
- _ba.set_camera_target(x: float, y: float, z: float) -> None
- _ba.set_camera_manual(value: bool) -> None

## Type of Changes

|   | Type |
| ------------- | ------------- |
| ✓  | :sparkles: New feature |

## Related Issue
#321

### CODE REVIEW

**Comment by IvanPragma** [comment]
@efroemling did I do everything right?

**Comment by efroemling** [comment]
> @efroemling did I do everything right?

Yes everything here looks cleanly implemented. Thanks for the contribution.
Though I've just enabled checks and it seems some are failing. Can you try running 'make preflight' and pushing any changes from that? It looks like it needs to update the dummy _ba.py file.

**Comment by IvanPragma** [comment]
> > @efroemling did I do everything right?
> 
> Yes everything here looks cleanly implemented. Thanks for the contribution. Though I've just enabled checks and it seems some are failing. Can you try running 'make preflight' and pushing any changes from that? It looks like it needs to update the dummy _ba.py file.

OK, I did it.

**Comment by efroemling** [comment]
There's a conflict in CHANGELOG.md now. Can you resolve that? (I'm happy to if you're busy.)

**Comment by IvanPragma** [comment]
Sure

**Comment by efroemling** [comment]
Dummy _ba module is out of sync with python sources again 😅. Can you do a `make preflight` one more time? So close...

**Comment by IvanPragma** [comment]
Ok, I ran `make preflight` again, but this time it didn't make any change

s.

**Comment by efroemling** [comment]
Are you sure? `git status` is showing nothing changed?
Anyway no worries; I'll fix it on my end if needed.

Thanks again for the contribution!
One note: I think I'll add a warning to the docs on these that they should only be used for tinkering or local games. (they're already 'internal' but just to be sure people know). Changing camera position directly won't actually be visible to network clients, probably will do crazy broken stuff in VR builds, etc. (but there's nothing wrong with tinkering).

**Comment by efroemling** [comment]
One more clarifying note: to support camera controls 'properly' we would need to wire it up to the node/scene system so that changes to it would be propagated on the network to all connected clients. But this also brings up a design decision: currently the game supports VR systems where direct camera control is not available, and any mini-games designed around direct camera control would probably be broken for them. (I know VR players would be a tiny percentage of the game's audience, but still worth considering).  But anyway I don't think it hurts anything to have these controls in there for people who want to play around with scripts. We should just make it clear that they aren't 'first-class' controls.

**Comment by IvanPragma** [comment]
Well, thanks!
> Are you sure? `git status` is showing nothing changed? Anyway no worries; I'll fix it on my end if needed.
> 
I'm using github desktop and it didn't show any changes.

**Pull request merged**
