### PR TITLE
Community Implementation #0: Discord Button

### PR DESCRIPTION
**Pull request by EraOSBeta**
## My Tasks

- [x] Write a good description of what your PR does (and WHY it does it).
- [x] Update CONTRIBUTORS.md.
- [x] Ensure `make preflight` completes successfully.

## Eric's Tasks

- [ ] Add a CHANGELOG entry.
- [ ] Replace all strings with Ballistica's language strings
- [ ] Add this texture to the game as 'discordPreview'
discordPreview

## Description

For quite a long time the official Discord server has been a quite place due to not receiving the needed promotions, specially from within the game itself, this PR adds a window for joining the discord and 2 buttons to access it (one on the Main Menu and one in Gather>About)

## Type of Changes
|     | Type                   |
|-----|------------------------|
| ✓   | :sparkles: New feature |

## Preview
Screenshot from 2023-11-10 13-18-50
Screenshot from 2023-11-10 13-19-09
Screenshot from 2023-11-10 13-19-28

### CODE REVIEW

**Comment by vishal332008** [comment]
The 2nd and 3rd image looks very good, but I think the 1st image may look a little weird in mobile. As Eric didn't release latest apk of bombsquad, i can't check it myself, so can you send the 1st image from a mobile or UI as small?
And it looks so different with just one button. But it's just my opinion. If Eric accepts it, then it's fine. I can tweak the button a little.

**Comment by EraOSBeta** [comment]
> The 2nd and 3rd image looks very good, but I think the 1st image may look a little weird in mobile. As Eric didn't release latest apk of bombsquad, i can't check it myself, so can you send the 1st image from a mobile or UI as small? And it looks so different with just one button. But it's just my opinion. If Eric accepts it, then it's fine. I can tweak the button a little later.

I haven't tested on mobile or different UI sizes since .apk release is still dying on the floor, but u can probably just edit the last .apk release, add this stuff to it, and see how it looks. (And also Eric will probably test to see how everything looks on different UI scales before merging so don't worry)

**Comment by vishal332008** [comment]
Eric, if you are adding this new so-called "DiscordPreview" image, don't remove the old original discord image. It may be useful for something.

**Comment by EraOSBeta** [comment]
> Eric, if you are adding this new so-called "DiscordPreview" image, don't remove the old original discord image. It may be useful for something.

Yeah there's no intent for removing previous assets since that asset is probably used in some servers anyways.

> And Era, we have to replace all the strings with ballistica language strings. It's our work. Eric will add them into the json files. It's his work.

I intentionally left the string so it's clear what the English translation is supposed to be, but I'll replace it later if Eric wants that before merging.

**Comment by efroemling** [comment]
Thanks for putting this together!

**Comment by efroemling** [comment]
Screenshot 2023-11-29 at 4 54 21 PM
Quick note: this is slightly broken on small screen sizes. I'm going to disable it for tonight's build but I'll get it fixed tomorrow.

**Comment by MatiasMGz** [comment]
Why in Gather? Though that button is for multiplayer, i think there are better places to put it.

**Pull request merged**
