### PR TITLE
Fixing a bug related to Plugin File Names.

### PR DESCRIPTION
**Pull request by vishal332008**
Fixed a bug where plugins don't run due to them being named same as inbuilt module from standard library of python.
Example : sys.py, os.py, etc.
Please check if this messes with anything else because this getclass function is used in other files too.

### CODE REVIEW

**Comment by efroemling** [comment]
This seems like a good check to have; thanks!
However can I request one change?: the getclass() function is supposed to be a generic thing that theoretically could be used with stuff in stdlib modules. Could we move this check up a level so the plugin-specific code makes the check *before* it calls getclass()?

**Comment by efroemling** [comment]
Alternately I'd be fine with having the check be in getclass but controlled by an optional arg like `check_sys_modules_name_clash` which defaults to False.

**Comment by vishal332008** [comment]
> Alternately I'd be fine with having the check be in getclass but controlled by an optional arg like `check_sdlib_modules_name_clash` which defaults to False.

I made some changes, hoping they are correct.

**Comment by efroemling** [comment]
Looks good; thanks!

**Pull request merged**
