### PR TITLE
Rotating Logo and some other fixes

### PR DESCRIPTION
**Pull request by vishal332008**

### CODE REVIEW

**Comment by vishal332008** [comment]
@efroemling 
- Added spinny logo. (You can remove it if it looks bad).
- Fixed positions in the coop score screen, advanced window title text, and a few things in controllers window.
- Added new mobile back button in touchscreen window.
- Fixed a pause/resume bug in coop games. (if you press the 3 lines on the right corner 2 times, first time the game pauses and the in_game_menu opens, but when you press it again, the in_game_menu goes away but game still remains paused).
- Fixed a bug where if you open the player profile window for creating/editing a profile in the area where you select the your profile to play in the game, the back and save buttons don't work.
- Fixed a bug where after pressing the send button in party window, the msg comes as a screen message instead of text in the chat.

Found a bug in in_game_menu. It doesn't show "leave game" for online servers, it only shows "leave party".

**Comment by vishal332008** [comment]
@efroemling 😭

**Comment by vishal332008** [comment]
I don't know how to fix this error. Please take care of this one. Other's all work perfectly.

**Comment by efroemling** [comment]
Thanks for this and sorry for making extra work for you. I'll get the CI issue fixed. Basically It's related to the fact that we have a single node type in Python so some attributes can be 'float' or Sequence['float'] depending on the actual underlying node in the C++ layer.

**Pull request merged**
