### PR TITLE
Sphinx docs generation

### PR DESCRIPTION
**Pull request by Loup-Garou911XD**
### Sphinx documentation
Added `docs-sphinx` and `docs-sphinx-clean` to make target for building sphinx documentation
Added `make_sphinx_docs` target to cd.yaml for building docs on push and pull requests 

Random notes:
- Sphinx has alot of themes which can be changed in src/assets/sphinx/template/conf.py

Screenshot from 2024-03-13 02-55-14
Screenshot from 2024-03-13 02-55-56

## Type of Changes
|     | Type                   |
|-----|------------------------|
| ✓   | :sparkles: New feature |

### CODE REVIEW

**Comment by Loup-Garou911XD** [comment]
@efroemling after generating dummy modules 
_babase.py
L868 in env()
`return dict`
causes error so all modules are not generated
Replacing it with `return {'locale':''}` fixes the error, but idk how to make sphinx ignore that

**Comment by Loup-Garou911XD** [comment]
Also dummymodules are generated every time for some reason(lazy build not working)

**Review by Loup-Garou911XD — COMMENTED** [review]
shouldn't have bothered cause i will break it again with another commit

**Comment by Loup-Garou911XD** [comment]
should i rebase for clean commit msg?

**Comment by Loup-Garou911XD** [comment]
how do i trigger ci run?

**Comment by Loup-Garou911XD** [comment]
@efroemling which formatter do u use?Also can i have the config for it.
Also how do i fix this?```Error copying/filtering file: '/home/loup/github_fork/ballistica/src/assets/sphinx/template/index.rst': No filter rule for path 'src/assets/sphinx/template/index.rst'. (use --verbose for full traceback)
```

**Comment by efroemling** [comment]
> @efroemling which formatter do u use?Also can i have the config for it. Also how do i fix this?

The project is using black these days. If you are able to run project commands, run 'make format' to trigger it. You can dig into the Makefile/pcommand call to see what args it passes/etc. (though black intentionally doesn't have too many options).

> ```
> Error copying/filtering file: '/home/loup/github_fork/ballistica/src/assets/sphinx/template/index.rst': No filter rule for path 'src/assets/sphinx/template/index.rst'. (use --verbose for full traceback)
> ```

This is the spinoff stuff (batools.spinoff) complaining because it doesn't know whether to filter stuff in a .rst file or not (replace 'ballisticakit' with 'bombsquad' or whatever the project name is, etc.) I'm guessing 'yes' would be the right answer. You an add '.rst' to 'cox.filter_file_extensions' in 'config/spinoffconfig.py' to make it do that.

**Comment by efroemling** [comment]
> should i rebase for clean commit msg?

In general I'm fine either way; whatever you prefer.

**Comment by Loup-Garou911XD** [comment]
> > should i rebase for clean commit msg?
> 
> In general I'm fine either way; whatever you prefer.



> > @efroemling which formatter do u use?Also can i have the config for it. Also how do i fix this?
> 
> The project is using black these days. If you are able to run project commands, run 'make format' to trigger it. You can dig into the Makefile/pcommand call to see what args it passes/etc. (though black intentionally doesn't have too many options).
> 
> > ```
> > Error copying/filtering file: '/home/loup/github_fork/ballistica/src/assets/sphinx/template/index.rst': No filter rule for path 'src/assets/sphinx/template/index.rst'. (use --verbose for full traceback)
> > ```
> 
> This is the spinoff stuff (batools.spinoff) complaining because it doesn't know whether to filter stuff in a .rst file or not (ie: replacing 'ballisticakit' with 'bombsquad' or whatever the project name is, etc.) I'm guessing 'yes' would be the right answer. You an add '.rst' to 'ctx.filter_file_extensions' in 'config/spinoffconfig.py' to make it do that.

Umm `make format changed 101 files`

**Comment by efroemling** [comment]
> ignore this cause working now Also dummymodules are generated every time for some reason(lazy build not working)

lazybuild should print a message saying which file changed to get it to rebuild stuff. Are you seeing anything like that?

**Comment by efroemling** [comment]
> > > should i rebase for clean commit msg?
> > 
> > 
> > In general I'm fine either way; whatever you prefer.
> 
> > > @efroemling which formatter do u use?Also can i have the config for it. Also how do i fix this?
> > 
> > 
> > The project is using black these days. If you are able to run project commands, run 'make format' to trigger it. You can dig into the Makefile/pcommand call to see what args it passes/etc. (though black intentionally doesn't have too many options).
> > > ```
> > > Error copying/filtering file: '/home/loup/github_fork/ballistica/src/assets/sphinx/template/index.rst': No filter rule for path 'src/assets/sphinx/template/index.rst'. (use --verbose for full traceback)
> > > ```
> > 
> > 
> > This is the spinoff stuff (batools.spinoff) complaining because it doesn't know whether to filter stuff in a .rst file or not (ie: replacing 'ballisticakit' with 'bombsquad' or whatever the project name is, etc.) I'm guessing 'yes' would be the right answer. You an add '.rst' to 'ctx.filter_file_extensions' in 'config/spinoffconfig.py' to make it do that.
> 
> Umm `make format` changed 101 files

Interesting. There's always a chance that's correct if black was just updated or something. If you do a `git diff` does it look like some nitpicky minor thing got changed in lots of places?

**Comment by Loup-Garou911XD** [comment]
> > ignore this cause working now Also dummymodules are generated every time for some reason(lazy build not working)
> 
> lazybuild should print a message saying which file changed to get it to rebuild stuff. Are you seeing anything like that?

dont worry its working fine now

**Comment by Loup-Garou911XD** [comment]
> > > > should i rebase for clean commit msg?
> > > 
> > > 
> > > In general I'm fine either way; whatever you prefer.
> > 
> > 
> > > > @efroemling which formatter do u use?Also can i have the config for it. Also how do i fix this?
> > > 
> > > 
> > > The project is using black these days. If you are able to run project commands, run 'make format' to trigger it. You can dig into the Makefile/pcommand call to see what args it passes/etc. (though black intentionally doesn't have too many options).
> > > > ```
> > > > Error copying/filtering file: '/home/loup/github_fork/ballistica/src/assets/sphinx/template/index.rst': No filter rule for path 'src/assets/sphinx/template/index.rst'. (use --verbose for full traceback)
> > > > ```
> > > 
> > > 
> > > This is the spinoff stuff (batools.spinoff) complaining because it doesn't know whether to filter stuff in a .rst file or not (ie: replacing 'ballisticakit' with 'bombsquad' or whatever the project name is, etc.) I'm guessing 'yes' would be the right answer. You an add '.rst' to 'ctx.filter_file_extensions' in 'config/spinoffconfig.py' to make it do that.
> > 
> > 
> > Umm `make format` changed 101 files
> 
> Interesting. There's always a chance that's correct if black was just updated or something. If you do a `git diff` does it look like some nitpicky minor thing got changed in lots of places?

yeah ig
```
@@ -93,8 +89,7 @@ class CloudSubsystem(babase.AppSubsystem):
         on_response: Callable[
             [bacommon.cloud.SignInResponse | Exception], None
         ],
-    ) -> None:
-        ...
+    ) -> None: ...
 
-        ...
+    ) -> None: ...
 
     @overload
     def send_message_cb(
@@ -67,24 +66,21 @@ class CloudSubsystem(babase.AppSubsystem):
         on_response: Callable[
             [bacommon.cloud.LoginProxyStateQueryResponse | Exception], None
         ],
-    ) -> None:
-        ...
+    ) -> None: ...
 
     @overload
     def send_message_cb(
         self,
         msg: bacommon.cloud.LoginProxyCompleteMessage,
         on_response: Callable[[None | Exception], None],
-    ) -> None:
-        ...
+    ) -> None: ...
 
     @overload
     def send_message_cb(
         self,
         msg: bacommon.cloud.PingMessage,
         on_response: Callable[[bacommon.cloud.PingResponse | Exception], None],
-    ) -> None:
-        ...
+    ) -> None: ...
 
     @overload
     def send_message_cb(
@@ -93,8 +89,7 @@ class CloudSubsystem(babase.AppSubsystem):
         on_response: Callable[
             [bacommon.cloud.SignInResponse | Exception], None
         ],
-    ) -> None:
-        ...
+    ) -> None: ...
```

**Comment by efroemling** [comment]
Haha; as a test I just ran `make format` myself and got 107 files changed, so it would appear that black has in fact changed its formatting recently.

**Comment by efroemling** [comment]
> > Haha; as a test I just ran `make format` myself and got 107 files changed, so it would appear that black has in fact changed its formatting recently.
> 
> will you commit those changes so i can pull or should i commit? it would make it hard for you to check the changes if i commit

I think I'll go ahead and commit those since I had a few other in-progress things I needed to push anyway. I'll do that right now. Hope that's ok.

**Comment by efroemling** [comment]
Ok latest stuff is up. Hopefully nothing tricky to merge. Thanks for doing this by the way!

**Comment by Loup-Garou911XD** [comment]
pls trigger workflows

**Comment by efroemling** [comment]
Settings say I only need to approve workflow runs for first-time-contributors, so hopefully once this is pulled in you won't have to wait for me to approve runs anymore.

**Comment by Loup-Garou911XD** [comment]
@efroemling
if i run `make format` i still get 100+ c++ files getting changed
maybe you only ran `format-scripts`?

**Comment by efroemling** [comment]
> @efroemling if i run `make format` i still get 100+ c++ files getting changed maybe you only ran `format-scripts`?

I actually had lots of C++ stuff change in my commit too, so I assume clang-format was updated recently. Maybe yours is older and is trying to change it back? (or vice versa?).  I'm running 18.1.1. How about you?

**Comment by Loup-Garou911XD** [comment]
> > @efroemling if i run `make format` i still get 100+ c++ files getting changed maybe you only ran `format-scripts`?
> 
> I actually had lots of C++ stuff change in my commit too, so I assume clang-format was updated recently. Maybe yours is older and is trying to change it back? (or vice versa?). I'm running 18.1.1. How about you?

oh yeah i am clang-format version 17.0.6

**Comment by Loup-Garou911XD** [comment]
@efroemling a little help with `Error copying/filtering file: '/home/runner/work/ballistica/ballistica/src/assets/sphinx/template/Makefile': No known formula to create project file: 'src/assets/sphinx/template/Makefile'. (use --verbose for full traceback)`

**Comment by efroemling** [comment]
> @efroemling a little help with `Error copying/filtering file: '/home/runner/work/ballistica/ballistica/src/assets/sphinx/template/Makefile': No known formula to create project file: 'src/assets/sphinx/template/Makefile'. (use --verbose for full traceback)`

Looking into it...

**Comment by Loup-Garou911XD** [comment]
sorry i keep forgetting stuff

**Comment by efroemling** [comment]
> sorry i keep forgetting stuff

No worries; I do the same. My internal repo is like 99% "oops one more thing" commits 😬

**Comment by Loup-Garou911XD** [comment]
lmk if you want any changes, ill do them tomorrow
otherwise its finished from my side

**Comment by efroemling** [comment]
Woohoo! Thanks again for this. I'll go ahead and pull it in now and feel free to submit any followup tweaks later. 🥳

**Pull request merged**
