### PR TITLE
QoL for Teams Sessions, FFA Sessions, and Servers

### PR DESCRIPTION
**Pull request by EraOSBeta**
## My Tasks
- [x] Write a good description of what your PR does (and WHY it does it).
- [x] Ensure `make preflight` completes successfully.
- [x] Add temp to CONTRIBUTORS

## Eric's Tasks
- [ ] Add the new `Lstr`s to the game's translations
- [ ] Add a CHANGELOG entry
- [ ] Lock the series length UI behind BombSquad Pro if that's the direction you want to go, make your decision BEFORE merging the PR

## Description
This PR:
- implements a simple override for `bascenev1.Session.max_players` on servers' config files that allows them to either:
   - let the session decide the max player count
   - override the max player count with their own preferred count
   - remove the max player count limit entirely
- adds UI for customizing the Series-Length of teams sessions and the Points-to-Win of FFA sessions (Idea originally by @3alTemp

## Type of Changes
|     | Type                   |
|-----|------------------------|
| ✓   | :sparkles: New feature |

## Testing
You can try out this PR on Windows, Mac, and Linux by downloading a build from [here](https://github.com/efroemling/ballistica/actions/runs/7309848583). Note that these builds have issues with loading some text (`Lstr`s)

## Preview
Server Config
Teams Series-Length UI
FFA Points-to-Win UI

### CODE REVIEW

**Comment by efroemling** [comment]
Can you resolve the changlog conflicts? Then I'd be happy to pull this in.

**Comment by EraOSBeta** [comment]
> Can you resolve the changlog conflicts? Then I'd be happy to pull this in.

Done :+1:

**Comment by efroemling** [comment]
Thanks for this and sorry for the slowness pulling it in. Will add the LStrs and consider whether to require pro for it..

**Comment by efroemling** [comment]
Ok I added lang entries and changelog notes. I'm not going to add a pro requirement. Holler if there's anything I forgot to do on my end, and thanks again!

**Pull request merged**
