### PR TITLE
Fixed issues from #368 

### PR DESCRIPTION
**Pull request by Drooopyyy**
## Steps

- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Add a CHANGELOG entry describing what your PR does.
- [x] Ensure `make preflight` completes successfully.
- [x] Write a good description on what the PR does.

## Type of Changes

|     | Type                   |
|-----|------------------------|
| ✓   | :bug: Bug fix          |
| ✓   | :sparkles: New feature |
| ✓   | :hammer: Refactoring   |
| ✓   | :scroll: Docs          |

### CODE REVIEW

**Comment by Drooopyyy** [comment]
-Dead players cant win race.
-Dead players cant interact with flags.

**Comment by efroemling** [comment]
Looks good; thanks! Can you get the checks fixed and add a changelog entry? Let me know if you get stuck on anything.

**Comment by Drooopyyy** [comment]
Thank you dliwk for helping me and fixing checks :) .

**Comment by Dliwk** [comment]
Looks like some logic mess in PythonClassNode::GetDelegate() which can return None even if doraise=True ([line 206][1])

[1]: https://github.com/efroemling/ballistica/blob/c3348afb404d998708d494b8963928390ef0afa6/src/ballistica/python/class/python_class_node.cc#L206

**Comment by Dliwk** [comment]
Ok I fixed a few things and now it works fine.

**Comment by Dliwk** [comment]
Didn't found how can I increment app build number so I added changelog entry under 1.7.1 :man_shrugging:

**Comment by efroemling** [comment]
> Didn't found how can I increment app build number so I added changelog entry under 1.7.1 🤷‍♂️

That works. I can move things to the 1.7.2 section if there are no more 1.7.1 builds (which is probably what I'll do).

Currently I have a script on the internal repo which handles changing build-number/version since there's a number of files across platforms that need to be changed. Maybe I can expose that but I'd need to make sure there's no weirdness with the internal lib thinking its one build number and the public repo bits thinking its another. Or maybe the internal lib should have a separate build number.

**Comment by efroemling** [comment]
> Looks like some logic mess in PythonClassNode::GetDelegate() which can return None even if doraise=True ([line 206](https://github.com/efroemling/ballistica/blob/c3348afb404d998708d494b8963928390ef0afa6/src/ballistica/python/class/python_class_node.cc#L206))

Oh wow yeah I think you're right. Good catch! Looks like it would be possible for the type checker to think you have a non-optional delegate type after the getdelegate() call but in reality you have None.
Would you want to add that fix to this PR?

**Comment by Dliwk** [comment]
> Oh wow yeah I think you're right. Good catch! Looks like it would be possible for the type checker to think you have a non-optional delegate type after the getdelegate() call but in reality you have None. Would you want to add that fix to this PR?

I'm tired a bit now, so I can add that tomorrow or you can do that yourself. And not sure where else could this be the case.

**Comment by efroemling** [comment]
> > Oh wow yeah I think you're right. Good catch! Looks like it would be possible for the type checker to think you have a non-optional delegate type after the getdelegate() call but in reality you have None. Would you want to add that fix to this PR?
> 
> I'm tired a bit now, so I can add that tomorrow or you can do that yourself. And not sure where else could this be the case.

Ok I'll try to get to it today. And yeah it could be a good idea to scan over similar code patterns where a 'doraise' is present to make sure we're not violating type promises anywhere else..

**Comment by efroemling** [comment]
> I'm tired a bit now, so I can add that tomorrow or you can do that yourself. And not sure where else could this be the case.

Ok I just added a fix for this in c3348afb404d998708d494b8963928390ef0afa6
I also looked through other calls with 'doraise' in the C layer and didn't see any other occurrences, but let's keep our eyes open for that sort of thing in the future. Thanks again for the heads-up.

And I'll go ahead and merge this now. Thanks @Drooopyyy for the fixes!

**Pull request merged**
