### PR TITLE
HEX support for advanced color picker

### PR DESCRIPTION
**Pull request by 3alTemp**
## Description

Derivate from my work-in-progress BombSquad mod. I thought having support for HEX codes in the advanced color picker would be a neat, extra little feature that'd be appreciated by those people who look for more color accuracy (the current advanced color picker always rounds all values to 2 decimals).

https://github.com/efroemling/ballistica/assets/79161340/13365fcc-85e8-4b54-b44e-96a5a6a3e3a9

### NOTE:  For this to work properly, it requires the ``clayStroke`` texture. It was made using a UI window and adding some filters and masks, leaving it gray and texture enough to show the color like the game would.
clayStroke

## Oh no! Our table!
|     | Type                   |
|-----|------------------------|
| ✓   | :sparkles: New feature |

### CODE REVIEW

**Comment by efroemling** [comment]
Nice addition!

I think my one nitpick is that it looks a bit broken with the 'clear text' X button overlapping the hex value. Could you widen everything just a bit or shrink that text box a bit or something so that doesn't happen?

**Comment by 3alTemp** [comment]
> I think my one nitpick is that it looks a bit broken with the 'clear text' X button overlapping the hex value. Could you widen everything just a bit or shrink that text box a bit or something so that doesn't happen?

That's a fair nitpick; I left it the way it is because the text looks nice centered and overall didn't look that crammed to me, but we could definitely make it space out the text like input queries usually do.

**Comment by efroemling** [comment]
I should mention another fix would be to disable to 'clear text field' button for this widget. I think there's a flag to do that.

**Comment by 3alTemp** [comment]
I... did not know that was a thing! 😨

**Comment by efroemling** [comment]
Oh looks like I'm misremembering. It doesn't draw that control in some situations such as when running on TV (since there's no way to press it there). But there's currently no way to explicitly deactivate it. I'll add one right now; should be very simple. Back in a few.

**Comment by efroemling** [comment]
Ok just added an `allow_clear_button` arg to the `textwidget()` call if you'd like to use that. Holler if it doesn't work. 
7c45d16155fd03c138a30a07e3b1c6bde1344672

**Comment by 3alTemp** [comment]
It seems to be behaving properly 🤠

**Comment by efroemling** [comment]
Thanks for this!

**Pull request merged**
