### PR TITLE
Epic mode in keepaway & kingofthehill & football & hockey

### PR DESCRIPTION
**Pull request by FAL-Guys**
|     | Type                   |
|-----|------------------------|
| ✓   | :sparkles: New feature |

Added Epicmode support for keepaway, kingofthehill, football & hockey

### CODE REVIEW

**Comment by efroemling** [comment]
Looks good overall. Though all existing epic-modes also override the game music to be ba.MusicType.EPIC. Could you do the same here or is there a reason you don't want to?

**Comment by Dliwk** [comment]
Maybe it makes sense to add epic mode support in football and hockey games too.

**Comment by FAL-Guys** [comment]
> Looks good overall. Though all existing epic-modes also override the game music to be ba.MusicType.EPIC. Could you do the same here or is there a reason you don't want to?

Done

**Comment by efroemling** [comment]
All looks good; thanks for adding this!

**Pull request merged**
