### PR TITLE
Spaz.curse(): self.curse_explode Timer Behavior Change

### PR DESCRIPTION
**Pull request by EraOSBeta**
## Steps

- [x] Write a good description of what your PR does (and WHY it does it).
- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Ensure `make preflight` completes successfully.
- [ ] Add a CHANGELOG entry if your change is non-trivial.
- [x] Add videos showcasing before and after the patch

## Description
with the current behavior, if you get cursed, then get a med-pack, and then get cursed again all within 5 seconds of getting the first curse powerup, you will explode based on the timer set from the first curse, meaning that you can get the second curse and explode 1 second after getting it instead of 5 (never seen it happen in vanilla bs but it seems possible), this small 1 line patch fixes that by making the timer behavior similar to other powerups

Old Behavior:

https://user-images.githubusercontent.com/100019405/208839409-efa1ab6d-d8a3-4a39-b310-06530a2f505d.mp4

New Behavior:

https://user-images.githubusercontent.com/100019405/208840095-f5b48347-b94f-4043-8a7b-7e3f692bc3f8.mp4

## Type of Changes

|     | Type                   |
|-----|------------------------|
| ✓   | :bug: Bug fix          |

### CODE REVIEW

**Comment by komasio71** [comment]
👏

**Review by Dliwk — APPROVED** [review]
I'd set `self._curse_timer` to None when handling health powerup message, but it seem to be unnecessary. :man_shrugging:

**Comment by EraOSBeta** [comment]
> I'd set `self._curse_timer` to None when handling health powerup message, but it seem to be unnecessary. 🤷‍♂️

Yeah, curse_explode checks to see if you're cursed or not so it doesn't really change anything, also can you run the checks on latest commit again? Black committed fail on the last one 🥲

**Comment by efroemling** [comment]
Good catch; thanks!

**Pull request merged**
