### PR TITLE
ballistica in docker :o

### PR DESCRIPTION
**Pull request by Loup-Garou911XD**
## Steps

- [x] Write a good description of what your PR does (and WHY it does it).
- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Add a CHANGELOG entry if your change is non-trivial.
- [x] Ensure `make preflight` completes successfully.

## Description
Added build system for docker which builds docker image with bombsquad server which could be deployed easily with docker on any system
Added `docker-build` and `docker-run` targets to make file

## Type of Changes

|     | Type                   |
|-----|------------------------|
| ✓   | :sparkles: New feature |

### CODE REVIEW

**Comment by MW2917** [comment]
so I have to write my fix into changelog with PR?

**Comment by Loup-Garou911XD** [comment]
> so I have to write my fix into changelog with PR?

yeah u should

**Comment by Loup-Garou911XD** [comment]
@efroemling https://github.com/efroemling/ballistica/actions/runs/9140752345/job/25134432953?pr=698#step:5:23
what to do bout this?
i checked tools/batools/spinoff/_context.py and it doesn't have the sphinx dir anymore so idk

**Comment by efroemling** [comment]
> @efroemling https://github.com/efroemling/ballistica/actions/runs/9140752345/job/25134432953?pr=698#step:5:23 what to do bout this? i checked tools/batools/spinoff/_context.py and it doesn't have the sphinx dir anymore so idk

The src/assets dir is a bit of a complicated beast as far as spinoff rules and things like that. Can you stick the Dockerfile in `config/docker/Dockerfile`? I think that may fix (or least improve) things.

**Comment by Loup-Garou911XD** [comment]
> > @efroemling https://github.com/efroemling/ballistica/actions/runs/9140752345/job/25134432953?pr=698#step:5:23 what to do bout this? i checked tools/batools/spinoff/_context.py and it doesn't have the sphinx dir anymore so idk
> 
> The src/assets dir is a bit of a complicated beast as far as spinoff rules and things like that. Can you stick the Dockerfile in `config/docker/Dockerfile`? I think that may fix (or least improve) things.

Okay sure just gimme few minutes I'll push

**Comment by Loup-Garou911XD** [comment]
Also @vishal332008 asks you to come on discord

**Comment by efroemling** [comment]
> > > @efroemling https://github.com/efroemling/ballistica/actions/runs/9140752345/job/25134432953?pr=698#step:5:23 what to do bout this? i checked tools/batools/spinoff/_context.py and it doesn't have the sphinx dir anymore so idk
> > 
> > 
> > The src/assets dir is a bit of a complicated beast as far as spinoff rules and things like that. Can you stick the Dockerfile in `config/docker/Dockerfile`? I think that may fix (or least improve) things.
> 
> Okay sure just gimme few minutes I'll push

If it's still giving you errors after that, don't worry about it; I can fix the spinoff stuff on my end after I pull the PR if that's the case.

**Comment by efroemling** [comment]
> Also @vishal332008 asks you to come on discord

Also just as an FYI: the error I was seeing is that spinoff didn't know whether or not to filter the Dockerfile. Check out config/spinoffconfig.py line 142 for where it determines that. If you relocate Dockerfile to under config/docker/ then it will be covered by one of those rules (we *do* want it to be filtered I think).

**Comment by Loup-Garou911XD** [comment]
> > Also @vishal332008 asks you to come on discord
> 
> Also just as an FYI: the error I was seeing is that spinoff didn't know whether or not to filter the Dockerfile. Check out config/spinoffconfig.py line 142 for where it determines that. If you relocate Dockerfile to under config/docker/ then it will be covered by one of those rules (we _do_ want it to be filtered I think).

filtered means not included in spinoff project?

**Comment by efroemling** [comment]
Thanks for this!

**Comment by efroemling** [comment]
> > > Also @vishal332008 asks you to come on discord
> > 
> > 
> > Also just as an FYI: the error I was seeing is that spinoff didn't know whether or not to filter the Dockerfile. Check out config/spinoffconfig.py line 142 for where it determines that. If you relocate Dockerfile to under config/docker/ then it will be covered by one of those rules (we _do_ want it to be filtered I think).
> 
> filtered means not included in spinoff project?

No; filtered just means that all instances of 'BallisticaKit' in the file are replaced with 'BombSquad' (or whatever else the project name is), and optionally other filtering is done too. Generally we want this for most things.

**Pull request merged**
