### PR TITLE
Added os.chdir() in ballistica_server.py

### PR DESCRIPTION
**Pull request by Awesome-Logic**
I realized the script couldn't be executed from other directories so I added the chdir function.
Now the script can be properly executed from anywhere.
If that was intended, feel free to reject the request. Also first pull request :)

### CODE REVIEW

**Comment by Awesome-Logic** [comment]
The unix check seems to be failing due to some formatting error. I tried to format the files using make format but it's giving me an error related to 0 workers.

**Comment by Awesome-Logic** [comment]
I had to manually format the files. `make format` seems broken for me

**Comment by efroemling** [comment]
Sounds good to me. If someone ever has a strange need to use a server script with a different dist dir or something we can always add an explicit flag for that. Thanks!

**Comment by efroemling** [comment]
> The unix check seems to be failing due to some formatting error. I tried to format the files using make format but it's giving me an error related to 0 workers.

Can you paste the exact error you are seeing here? (or traceback or whatever it gives you). I'd love to fix that for you. `make format` is such a time saver...

**Pull request merged**
