### PR TITLE
New meta-tag '# ba_meta export keyboard'

### PR DESCRIPTION
**Pull request by Dliwk**
A new feature that provides a meta tag for custom keyboards offered in #137.

- To change keymap/keyboard quick press space two times.
- Keyboard may have unlimited pages with some extra chars or letters.

A word about standard emojis (#123)... Currently only Android (and Apple) devices can render them (this mentioned in #45) so is using them in all platfoms correct? For example, I see following:
изображение

### CODE REVIEW

**Comment by efroemling** [comment]
This is great!
Notes:
- In response to your question: most people playing the game will be on platforms like Android that *can* display full unicode such as Emoji, so I think it's ok to assume they exist and just have blank buttons otherwise. My goal is to get support added to all platforms eventually so this should not be an issue forever. Or if you feel like it, you can do something similar to the language pop-up which only displays some languages when full unicode is available. I just added a _ba.can_display_full_unicode() function if you'd like to go this route.
- It appears that there is no unicode page on the default keyboard now (at least looking at it from the Mac prefab build); is this intentional? Could you add a screenmessage() error if they tap that button and there are no pages available or something to that effect? Currently it just does nothing which feels slightly broken. If you'd like to add an error message entry to assets/src/ba_data/data/languages/english.json and use a `ba.Lstr(resource='yourErrorMessageText')` to display it then it'll get translated to all languages (eventually).
- Same deal with double-clicking space; by default there is only one keyboard so it feels slightly broken in that it just silently prints a space and then deletes it. Could you have it perhaps print a screen-message about which keyboard it is switching to or mention that there are none available?

Anyway, thanks for contributing this! Looking forward to pulling it in.

**Comment by Dliwk** [comment]
Ok; can someone check emojis?

**Comment by efroemling** [comment]
Thanks for the changes; everything looks good to me. (emojis aren't showing up because they aren't drawable in the current prefab builds, but I'll test them on Android/Mac BombSquad builds to make sure they work). I'll get resources added for your text strings.

My one thought is that it is a little ugly having the 'press double-space to switch keyboards' instruction visible at all times since the vast majority of people won't install extra keyboards. I might change it so that message only shows up if there is more than one keyboard present.

Thanks again for this!

Would you by chance want to add an entry on the [Knowledge Nuggets](https://github.com/efroemling/ballistica/wiki/Knowledge-Nuggets) page showing how to make a custom keyboard? (or an entire dedicated wiki page if you want). That might help get people using this functionality. Or if you feel like it is documented well enough in the source code for people to discover it then that works too 👍

**Comment by Dliwk** [comment]
Uh-oh; I missed a little bit, could you move assets/src/ba_data/python/keyboards.py in bastd?

**Comment by efroemling** [comment]
No worries; I'm in the process of doing that right now :).  I'm putting it in bastd/keyboard/englishkeyboard.py
I'm also modifying the code a bit in _get_keyboard() so that it supports nested module names such as bastd.keyboard.englishkeyboard.EnglishKeyboard and adding text resources for the strings so they get translated.
I should have a commit up soon...

**Comment by Dliwk** [comment]
Great, thanks!

I finished [Knowledge Nuggets](https://github.com/efroemling/ballistica/wiki/Knowledge-Nuggets#hello-world-3-creating-a-new-keyboard) page, but I still don't really like it, I couldn't write much there. When you have some free time, can you check it out?

**Comment by efroemling** [comment]
Ok I've pushed commit 0a625831ae7d4897ebd326b1be3717f4687682ea with my tweaks to the keyboard stuff. Let me know if anything looks odd to you.

And I think your knowledge-nuggets entry looks good! I just made some minor adjustments such as mentioning that the user might want to turn on 'Always Use Internal Keyboard' to be able to see the results easier.

Thanks again for doing this! Much appreciated 😁

**Pull request merged**
