### PR TITLE
Added workflow for deploying docs to github pages

### PR DESCRIPTION
**Pull request by Loup-Garou911XD**
## Steps

- [x] Write a good description of what your PR does (and WHY it does it).
- [x] Add yourself to CONTRIBUTORS if you are a new contributor.
- [x] Add a CHANGELOG entry if your change is non-trivial.
- [x] Ensure `make preflight` completes successfully.

## Description
Added a workflow for deploying sphinx docs to github pages

## Type of Changes

|     | Type                   |
|-----|------------------------|
| ✓   | :sparkles: New feature |
| ✓   | :scroll: Docs          |

## Expected from repository owner
allow the deployment in settings>pages by setting it to deploy by workflow

### CODE REVIEW

**Comment by efroemling** [comment]
Thaaaanks!

**Comment by efroemling** [comment]
Oops no thanks yet. I see this is still a draft.

**Comment by Loup-Garou911XD** [comment]
> Oops no thanks yet. I see this is still a draft.

yes for some reason its not getting triggered on push
trying to find out why

**Comment by Loup-Garou911XD** [comment]
wow linux arm64 gui debug build task takes significantly longer
guess is that its much bigger in size so takes longer to upload

**Comment by Loup-Garou911XD** [comment]
@efroemling ready to merge

**Comment by efroemling** [comment]
Thanks for this (for real this time!)

**Pull request merged**
