### PR TITLE
Runaround - Heartbeat behavior

### PR DESCRIPTION
**Pull request by SoK05**
## Description
Originally made by Temp in BombSquad: Explodinary, decided to port it to Vanilla because it's a non-invasive change and makes game UI a bit more lively!
When lives in Runaround drop to 4, the heart will start to beat - the fewer lives, the faster it beats!

Preview: https://youtu.be/7ijYnQRKkFM

## Type of Changes

|     | Type                   |
|-----|------------------------|
| ✓   | :sparkles: New feature |

### CODE REVIEW

**Comment by 3alTemp** [comment]
:o

**Comment by komasio71** [comment]
Yes erof pls add this

**Comment by 3alTemp** [comment]
Damn, GitHub displayed that TERRIBLY compared with the VSC preview lmao.

**Review by 3alTemp — APPROVED** [review]
Can I just approve this and do it myself?

**Comment by 3alTemp** [comment]
I'm tired, boss.

**Comment by efroemling** [comment]
Super cool; thanks for this!

**Pull request merged**
